services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - '3000:3000'
    restart: unless-stopped

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      PORT: 3000
    expose:
      - '3000'
    restart: unless-stopped
